name: Workflow dispatch

on:
  workflow_dispatch:

jobs:
  run:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

    - name: Environment Variables
      env:
        CURRENT_DATE: '2024-10-26'
      run: |
        echo "CURRENT_DATE: $CURRENT_DATE"
        echo "Linux date: $(date)"
        echo "Github context date: ${{ github.event.repository.pushed_at }}"

    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: List Directory Content
      run: ls -al

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Repository Content
      run: ls -al
      
    - name: List Environment Variables
      run: env

    - name: List Processes
      run: ps aux

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
